### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by urbankaiote** [povdocs/sync-player#1]
This looks awesome - but I've tried the demo on a bunch of devices and can't seem to get any video to play. Is there a recommended browser version?

**Comment by brianchirls** [comment]
Good catch. Our time server is down right now, due to some network shenanigans we've been having here. I'll look into getting it back up.

If you'd like to try running it yourself, you should be able to clone the repo and run your own server. It's included.

**Comment by brianchirls** [comment]
Restarted the server. Should be working. @urbankaiote can you confirm that it works for you?

**Comment by urbankaiote** [comment]
Still doesn't play the video here. Time sync still seems to work (ie. the
counter), but video doesn't play. Dev tools showing errors:

Specified "type" attribute of "video/mp4" is not supported. Load of media
resource http://pov-tc.pbs.org/pov/flv/2014/koch-mid.mp4 failed. public
"video metadata" 149.619 960 540 main.js:86
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
remote resource at http://digital.pov.org:8080/time-server/info. This can
be fixed by moving the resource to the same domain or enabling CORS.

I can manually play the video by right clicking and showing the controls
but they don't sync with the time-server. I'm on a mac and tried in
chrome/safari/firefox but same result in all.

**Comment by brianchirls** [comment]
The server was crashing with a pretty cryptic error. I updated the dependencies, and it seems to be better for the moment. That should take care of the Cross-Origin error.

As for playing the mp4, what browser and version are you using? It should fall back to the webm even if it can't load mp4.

**Comment by urbankaiote** [comment]
Whatever it was - it's fixed and working! I'm gonna have a play with the
latency detection across devices - will let you know how I go. It's super
cool though! Thanks for taking the time to respond.

**Comment by brianchirls** [comment]
Glad that worked out. If you hadn't posted here, I would've gone a long time before noticing that this was down.

I'll close this issue for now, but please follow up with any feedback.
